
test-A:
	cd A && oj t -c "go run main.go"

test-B:
	cd B && oj t -c "go run main.go"

test-C:
	cd C && oj t -c "go run main.go"

test-D:
	cd D && oj t -c "go run main.go"

test-E:
	cd E && oj t -c "go run main.go"

random-A:
	./scripts/script-a.sh

random-B:
	./scripts/script-b.sh

random-C:
	./scripts/script-c.sh

random-D:
	./scripts/script-d.sh

